
export const CREATE_TODO_SUCCESS = 'CREATE_TODO_SUCCESS';
export const FETCH_TODO_SUCCESS = 'FETCH_TODO_SUCCESS';
export const UPDATE_TODO_SUCCESS = 'UPDATE_TODO_SUCCESS';
export const DELETE_DATA_SUCCESS = 'DELETE_DATA_SUCCESS';
export const CHECK_DATA_SUCCESS = 'CHECK_DATA_SUCCESS';
